### ISSUE TITLE
Cannot create pull requests for this repo.

### ISSUE THREAD

**Issue by kwsorensen** [spacesiren/spacesiren#3]
Was hoping to contribute and cannot create a branch/pull request. Can you add me?

**Comment by khicks** [comment]
Hmmm, you should be able to create pull requests. In fact, we had someone else do it earlier today (#2).

Make sure you fork the repo, make any changes you'd like in your copy, then make a new PR over here, clicking "compare across forks".

**Comment by khicks** [comment]
@kwsorensen, If I may ask, what kind of contribution did you have in mind?

**Comment by khicks** [comment]
Hey @kwsorensen, I haven't heard from you in a while, so I'm going to close this issue. Let me know if you need anything else.
